name: Reminder Plugins CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_foodreminder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    - name: Create local.properties
      run: echo "sdk.dir=${ANDROID_HOME}" > local.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run tests for foodreminder
      run: ./gradlew :foodreminder:test

  test_medicationreminder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    - name: Create local.properties
      run: echo "sdk.dir=${ANDROID_HOME}" > local.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run tests for medicationreminder
      run: ./gradlew :medicationreminder:test

  test_waterreminder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    - name: Create local.properties
      run: echo "sdk.dir=${ANDROID_HOME}" > local.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run tests for waterreminder
      run: ./gradlew :waterreminder:test